// <auto-generated />
using BD_SuperZapatos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BD_SuperZapatos.Migrations
{
    [DbContext(typeof(DbContextSuperZapatos))]
    partial class DbContextSuperZapatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BD_SuperZapatos.Models.Articles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("store_id")
                        .HasColumnType("int");

                    b.Property<int>("total_in_shelf")
                        .HasColumnType("int");

                    b.Property<int>("total_in_vault")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("store_id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BD_SuperZapatos.Models.Stores", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("BD_SuperZapatos.Models.Articles", b =>
                {
                    b.HasOne("BD_SuperZapatos.Models.Stores", "store")
                        .WithMany()
                        .HasForeignKey("store_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("store");
                });
#pragma warning restore 612, 618
        }
    }
}
